# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['index.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'anthropic',
        'openai',
        'github',
        'pygithub',
        'urllib3',
        'certifi',
        'charset_normalizer',
        'idna',
        'requests',
        'typing_extensions',
        'pydantic',
        'pydantic_core',
        'annotated_types',
        'httpx',
        'httpcore',
        'h11',
        'anyio',
        'sniffio',
        'distro',
        'tqdm',
        'colorama',
        'pyjwt',
        'wrapt',
        'deprecated',
        'dateutil',
        'nacl',
        'cffi',
        'pycparser',
        'cryptography',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='release-notes-pls',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
